# -*- coding: utf-8 -*-
"""生成策略模块介绍 PDF - 使用document-skills:pdf技能指南"""

from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

# 注册中文字体
try:
    pdfmetrics.registerFont(TTFont('MicrosoftYaHei', 'C:/Windows/Fonts/msyh.ttc'))
    chinese_font = 'MicrosoftYaHei'
except:
    chinese_font = 'Helvetica'

# 创建 PDF
doc = SimpleDocTemplate(
    "D:/llm_customer_service/doc/policy_skill.pdf",
    pagesize=A4,
    rightMargin=2*cm,
    leftMargin=2*cm,
    topMargin=2*cm,
    bottomMargin=2*cm,
)

styles = getSampleStyleSheet()

# 自定义样式
title_style = ParagraphStyle(
    'CustomTitle',
    parent=styles['Title'],
    fontName=chinese_font,
    fontSize=20,
    spaceAfter=20,
    alignment=1,
)

h1_style = ParagraphStyle(
    'Heading1',
    parent=styles['Heading1'],
    fontName=chinese_font,
    fontSize=14,
    spaceAfter=10,
    spaceBefore=15,
)

h2_style = ParagraphStyle(
    'Heading2',
    parent=styles['Heading2'],
    fontName=chinese_font,
    fontSize=12,
    spaceAfter=8,
)

normal_style = ParagraphStyle(
    'Normal',
    parent=styles['Normal'],
    fontName=chinese_font,
    fontSize=10,
    spaceAfter=8,
)

story = []

# 标题
story.append(Paragraph("Policy 策略模块介绍", title_style))
story.append(Spacer(1, 0.3*cm))

# 1. 核心概念
story.append(Paragraph("1. 核心概念", h1_style))
story.append(Paragraph("""
Policy（策略）负责根据当前对话状态预测下一步应该执行的动作。
它是对话系统的"大脑"，决定当前回合应该做什么。
""", normal_style))
story.append(Spacer(1, 0.2*cm))

# 2. 类结构
story.append(Paragraph("2. 类结构", h1_style))
story.append(Paragraph("""
<pre>
Policy (抽象基类)
    ├── FlowPolicy              优先级 100 (最高)
    └── EnterpriseSearchPolicy  优先级 50  (中等)

PolicyEnsemble           策略管理器
</pre>
""", normal_style))
story.append(Spacer(1, 0.2*cm))

# 3. PolicyEnsemble 执行流程
story.append(Paragraph("3. PolicyEnsemble 执行流程", h1_style))
story.append(Paragraph("""
<pre>
用户消息 → Agent
    ↓
PolicyEnsemble.predict()
    ↓
按优先级遍历策略（高→低）
    ↓
选择第一个非放弃且置信度最高的预测
    ↓
返回 PolicyPrediction(action, confidence, ...)
</pre>
""", normal_style))
story.append(Spacer(1, 0.2*cm))

# 4. FlowPolicy
story.append(Paragraph("4. FlowPolicy (flow_policy.py)", h1_style))
story.append(Paragraph("""
<b>职责</b>：执行预定义的 Flow 流程
<br/>
<b>优先级</b>：100（最高）
<br/>
<b>触发条件</b>：当对话栈中有活动的 FlowStackFrame 时
""", normal_style))

story.append(Paragraph("工作流程：", h2_style))
story.append(Paragraph("""
1. 检查是否有活动的 Flow
2. 获取当前步骤
3. 执行步骤并确定动作
4. 更新对话状态
""", normal_style))
story.append(Spacer(1, 0.2*cm))

# 5. EnterpriseSearchPolicy
story.append(Paragraph("5. EnterpriseSearchPolicy", h1_style))
story.append(Paragraph("""
<b>职责</b>：知识库检索 + 降级机制
<br/>
<b>优先级</b>：50（中等）
""", normal_style))

story.append(Paragraph("降级链（Fallback Chain）：", h2_style))
story.append(Paragraph("""
<pre>
1. SearchStackFrame    → 检索知识库 → RAG回答
2. ChitChatStackFrame → 闲聊回答
3. CannotHandleStackFrame → 降级响应
4. CompletedStackFrame → 询问其他需求
5. HumanHandoffStackFrame → 人工转接
</pre>
""", normal_style))
story.append(Spacer(1, 0.2*cm))

# 6. PolicyPrediction
story.append(Paragraph("6. PolicyPrediction 数据结构", h1_style))
story.append(Paragraph("""
<pre>
@dataclass
class PolicyPrediction:
    action: Optional[str]      # 执行的动作
    confidence: float         # 置信度 0.0-1.0
    events: List[Dict]       # 附带事件
    metadata: Dict           # 额外数据
    policy_name: str       # 产生预测的策略名
</pre>
""", normal_style))

story.append(Paragraph("关键方法：", h2_style))
story.append(Paragraph("""
<pre>
is_abstain: 判断是否放弃预测
abstain(): 工厂方法创建放弃结果
</pre>
""", normal_style))
story.append(Spacer(1, 0.2*cm))

# 7. 关键方法
story.append(Paragraph("7. 关键方法速查", h1_style))
story.append(Paragraph("""
<pre>
文件                     方法              职责
-----------------------------------------------------------------
policy_ensemble.py       predict()        核心预测入口
flow_policy.py           predict()       执行 Flow 步骤
enterprise_search_policy.py  predict()    检索+降级处理
</pre>
""", normal_style))

story.append(Spacer(1, 0.5*cm))
story.append(Paragraph("Generated by Claude Code (using document-skills:pdf)", normal_style))

# 构建 PDF
doc.build(story)
print("PDF 生成成功: doc/policy_skill.pdf")